import './globals.css'
import Link from 'next/link'
import LoginBtn from './component/LoginBtn'
import LogOutBtn from './component/LogOutBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  return (

    <html lang="en">
      <body>
        <div className='navbar'>
          <Link href='/' className="logo">Appleforum</Link>
          <Link href='/list'>List</Link>
          {
            session ? <div>{session.user.name}<LogOutBtn/></div>: <LoginBtn/>
          }
        </div>
        {children}
        </body>
    </html>
  )
}
